### ISSUE TITLE
Anpassungen Link und Shop Tabel

### ISSUE THREAD

**Issue by b0rn2my** [b0rn2my/MyPizzaSessionApp#102]
Punkte im Footer weg. 

Button weg dafür Link mit Traget=_blank. 
Testen ob ein zweites Fenster bei der WPA öffnet. 

Wenn keine Beschreibung eingegeben ist dann dies leer lassen. ggf. height 100%

![image](https://github.com/user-attachments/assets/22819c39-054f-4859-a701-7c3846052ae6)

**Comment by b0rn2my** [comment]
Überschrift anpassen.

**Comment by b0rn2my** [comment]
Anordnung Random machen

**Comment by N0M3X** [comment]
Anpassung der "Pizza Links" anlog zu den "Partner" Feldern

![1](https://github.com/user-attachments/assets/48f9a7de-dd41-49a6-a5a7-939d5796d8fb)
