### ISSUE TITLE
Pizza veröffentlichen inklusive Voting

### ISSUE THREAD

**Issue by b0rn2my** [b0rn2my/MyPizzaSessionApp#11]
User sollen die Möglichkeit haben, erstellte Pizzas zu veröffentlichen.
Auf einer Seite werden die Pizzas dargestellt.
Rating auf die Pizza sollte möglich sein.

Löschen, Editieren möglich.
Zutaten verändern ebenfalls.

Aktuelle Pizza-Card
![image](https://github.com/b0rn2my/MyPizzaSessionApp/assets/101136546/6e726681-1bf7-42e3-a6f1-0a96b39c83e9)

**Comment by N0M3X** [comment]
Würde soweit passen, nur die abgegebenen Bewertungen (In diesem Beispiel 4) würde ich etwas anders anordnen

**Comment by b0rn2my** [comment]
> Würde soweit passen, nur die abgegebenen Bewertungen (In diesem Beispiel 4) würde ich etwas anders anordnen

Wie würdest du dies verändern? Kleiner und eine Überschrift (z.B. deine Bewertung)

**Comment by b0rn2my** [comment]
![image](https://github.com/b0rn2my/MyPizzaSessionApp/assets/101136546/676a3f5b-3f19-4d74-81e7-e918e4f3f8d0)

Denke so ungefähr. 
Mit einem extra Button "Bewerten" dann könnte man auch Kommentare hinterlegen wenn man die Bewertung auf einer extra Seite durchführt.

**Comment by b0rn2my** [comment]
@N0M3X 

![image](https://github.com/b0rn2my/MyPizzaSessionApp/assets/101136546/15360620-5f00-4eb0-9573-438378e32c62)


Das wäre nun der Stand... die Seite für das Rating muss ich noch machen.
