### ISSUE TITLE
Kontakt Seite

### ISSUE THREAD

**Issue by b0rn2my** [b0rn2my/MyPizzaSessionApp#12]
Eingaben für E-Mail
Antwort an EMail

ggf. auch GitHub integrieren

**Comment by b0rn2my** [comment]
@N0M3X wie besprochen könntest du die Seite ein wenig designen wie du möchtest auch den Inhalt.
Leider hat das Kontaktformular Nachteile die ich leider nicht sicher gestalten kann.

So sieht es aktuell aus:


![Image](https://github.com/b0rn2my/MyPizzaSessionApp/assets/101136546/a82bb64f-7bc5-45b3-8b8e-d1f78caaa04e)

**Comment by N0M3X** [comment]
Dein Text oben passt schon recht gut. Würde die Seite jetzt nicht überladen und habe nur die Ansprache in die Du-Form gesetzt sodass es zur restlichen Seite passt. Was meint ihr zu folgendem Vorschlag. Fehlt euerer Meinung nach noch was?

**Kontakt**

Hast du Fragen oder Anregungen oder benötigst unsere Unterstützung?
Dann schreibe uns gerne eine E-Mail an **support@mypizzasession.de**.
Wir freuen uns darauf von dir zu hören.
