### ISSUE TITLE
Bild für neue Sessions hinterlegen

### ISSUE THREAD

**Issue by N0M3X** [b0rn2my/MyPizzaSessionApp#16]
Was hältst du davon wenn man ein Bild (ähnlich wie beim Anlegen von Zutaten, Pizzen) beim Erstellen einer neuen Session hinzufügen kann und die Gäste dieses Bild dann auf der Landing Page für die Bestellung sehen.

**Comment by b0rn2my** [comment]
Wäre möglich und auch nicht viel Aufwand verbunden. Könnte im E-Mail ebenfalls mit verschickt werden. Würde es aber nicht anzeigen wenn keines vorhanden. Sonst würde da ja meistens No-Image-Available stehen. 

Hätte da auch an das Profilbild des Users gedacht. 

Session von XYZ Progilbild. 
Session Name
Session Bild.

**Comment by N0M3X** [comment]
Ja, klingt klasse. Und wie du sagst wenn kein's gewählt wird dann nichts anfügen
