### ISSUE TITLE
Aussagekräftiges Logo erstellen.

### ISSUE THREAD

**Issue by b0rn2my** [b0rn2my/MyPizzaSessionApp#18]

**Comment by b0rn2my** [comment]
![image](https://github.com/b0rn2my/MyPizzaSessionApp/assets/101136546/f387cfe0-1a42-4629-bf97-b23c9185d872)

![image](https://github.com/b0rn2my/MyPizzaSessionApp/assets/101136546/fcb21fc9-de4b-4c1a-b564-eda39a08bdd2)

**Comment by b0rn2my** [comment]
Eingabe in ChatGPT:

Logo für eine App darauf soll ein Einkaufszettel, eine Pizza, Personen und Grillfleisch zu sehen sein.

**Comment by b0rn2my** [comment]
@N0M3X sowas in der Art?

![image](https://github.com/b0rn2my/MyPizzaSessionApp/assets/101136546/4b4bb56a-e01f-431e-bb3a-729cebe99282)

![image](https://github.com/b0rn2my/MyPizzaSessionApp/assets/101136546/79b66eba-9b74-4539-a6a5-49dc03c39fad)

**Comment by N0M3X** [comment]
Ja solche Bilder habe ich auch erhalten. War aber noch nichts dabei wo ich gesagt hätte das ist es.

**Comment by N0M3X** [comment]
Hab mal neue Logo gebastelt. Was hältst du davon? Gefallen die dir von der Optik her? Hätte als Schlagworte Pizza, Einkaufszettel und Handy gewählt. Wenn die Logos dir so passen, könnte ich mal welche mit kommerzieller Nutzung erstellen...

**Comment by N0M3X** [comment]
![image](https://github.com/b0rn2my/MyPizzaSessionApp/assets/166199140/6cf66943-88fe-4fdb-a64c-0a7aac08228a)

**Comment by N0M3X** [comment]
![image](https://github.com/b0rn2my/MyPizzaSessionApp/assets/166199140/1b517590-6808-4316-9a9b-76a631fb4a58)

**Comment by N0M3X** [comment]
![image](https://github.com/b0rn2my/MyPizzaSessionApp/assets/166199140/15a11910-2d53-4947-adf3-8b0a3754a63d)

**Comment by N0M3X** [comment]
![image](https://github.com/b0rn2my/MyPizzaSessionApp/assets/166199140/9fbebf7c-97d9-4cde-b9a1-7c2c8839be6b)

**Comment by b0rn2my** [comment]
> ![image](https://private-user-images.githubusercontent.com/166199140/321900138-15a11910-2d53-4947-adf3-8b0a3754a63d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MTM5NDUsIm5iZiI6MTcxMjkxMzY0NSwicGF0aCI6Ii8xNjYxOTkxNDAvMzIxOTAwMTM4LTE1YTExOTEwLTJkNTMtNDk0Ny1hZGYzLThiMGEzNzU0YTYzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMlQwOTIwNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYzU1NWY1ZmY3MDFiNGI0ZDBhNWFhZmYwYjMxNTY5YWM0NzExY2E5NWQ5NjVlN2JkYWI4YmMzYzdiZTUxM2M4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xvyCO8NsjKx-Tj8XrgNKtQJHrVYbjxycAeFn9n6vVhI)

Das gefällt mir bis jetzt am besten

**Comment by N0M3X** [comment]
Welches genau?

**Comment by b0rn2my** [comment]
Das 3. in der Liste

**Comment by N0M3X** [comment]
Finde das hier klasse

![image](https://github.com/b0rn2my/MyPizzaSessionApp/assets/166199140/89163f80-a216-4ed1-861f-cdd353da4071)

**Comment by b0rn2my** [comment]
Das gefällt meiner Frau auch am besten. 
Wenn du möchtest kannst da eines erstellen. 
Ich mache daraus dann eine png ohne Hintergrund. 
Dann noch die ICON Dateien für das App Symbol. 

![image](https://github.com/b0rn2my/MyPizzaSessionApp/assets/101136546/33c29639-97e8-4f85-b6da-0aaac8d72420)

**Comment by N0M3X** [comment]
Habe jetzt mal einige Logos mit dem Premium Account für kommerzielle Nutzung erstellt. 
Schau mal ob hier was für dabei ist...

![8-43Zd2TRLT3hVWWf](https://github.com/b0rn2my/MyPizzaSessionApp/assets/166199140/4dd61e9c-2b79-4d3e-96bb-8f22503e0de5)
![8-AWoMk9p0SPQ0eST](https://github.com/b0rn2my/MyPizzaSessionApp/assets/166199140/b25a9196-0185-4b4f-a3c1-3759881b6768)
![8-B21VE0AKzojz2Zh](https://github.com/b0rn2my/MyPizzaSessionApp/assets/166199140/36f4b72e-3b44-4026-9f4b-da5a0e836fab)
![8-jdxKxTrJoimeoow](https://github.com/b0rn2my/MyPizzaSessionApp/assets/166199140/c12acc97-8f07-4b9f-af17-766bfec7f7bb)
![8-LyNR3zLdLCmaiLZ](https://github.com/b0rn2my/MyPizzaSessionApp/assets/166199140/10f9f378-2b80-4fc7-95f9-9f794aff9830)
![8-sh2rDFpAU1pdm8Q](https://github.com/b0rn2my/MyPizzaSessionApp/assets/166199140/5b09e1bc-4348-4359-810c-ed53c859fe4c)
![8-SqO4k0Y9mxJyjP1](https://github.com/b0rn2my/MyPizzaSessionApp/assets/166199140/98c03ea5-f45a-4507-af09-87c460fc35da)
![8-UH8SYGo9mgqk1Pr](https://github.com/b0rn2my/MyPizzaSessionApp/assets/166199140/8e25b6ad-d1c9-4ffc-9c6c-37e1c7a67f8f)
![8-WXH6sVrvMYaT20T](https://github.com/b0rn2my/MyPizzaSessionApp/assets/166199140/71c9dea2-037c-4bb1-a31e-984b36f48bac)

**Comment by b0rn2my** [comment]
Falls dich die Logos viel gekostet haben dann sag Bescheid. Ich beteilige mich da natürlich. 

Ich finde das 3. am besten. 
Darf ich die noch bearbeiten?

**Comment by N0M3X** [comment]
Ich nutzte den Premium Account auch noch für was anderes, von daher fallen die paar Bilder erstmal nicht ins Gewicht. Aber trotzdem danke.

Ich kann noch ein Paar erstellen, dann haben wir eine größere Auswahl.

Bezüglich Bearbeitung denke ich spricht nichts dagegen, da schick ich dir mal die AGBs durch. Hier steht mit Premium darf man die kommerziell nutzen, allerdings ist halt kein Copyright drauf.

**Comment by N0M3X** [comment]
Hier noch die AGB's. Schicke später noch einige Logos durch...

**Comment by N0M3X** [comment]
Can I use Hotpot graphics and text commercially?

Yes, if you buy credits or buy a license.

Note this only authorizes you to use Hotpot for commercial reasons.

This does not constitute copyright or intellectual property protection. We cannot guarantee uniquess anymore than Photoshop or Microsoft Word. It is conceivable for someone to produce similar or even identical content with other software or AI. This means any logo, text, or graphic produced on Hotpot could be made elsewhere.

Treat Hotpot as an AI helper who sparks creativity and automates drudgery -- but not someone who verifies compliance with intellectual property laws.

Ultimately, Hotpot is nothing but a general tool that produces graphics and text guided by a human.

It is your responsibility to produce unique content that honors local and international laws. To personalize graphics more easily, use unique seed images with [AI Art Generator](https://hotpot.ai/art-generator) or [AI Art Remixer](https://hotpot.ai/personalize-art).

We may use invisible watermarks to identify Hotpot creations for legal disputes.

**Comment by N0M3X** [comment]
So hier hab ich noch einen Schwung...

![8-05pFUnzUYQEPsI6](https://github.com/b0rn2my/MyPizzaSessionApp/assets/166199140/2a0e38c0-1a08-4035-b9a0-99415a1d1c1d)
![8-9ok1FqPTGg6v8xN](https://github.com/b0rn2my/MyPizzaSessionApp/assets/166199140/43c0b5f7-18a5-470b-8bb9-d4b7ea24eec1)
![8-GIO7f4C4olCHqFL](https://github.com/b0rn2my/MyPizzaSessionApp/assets/166199140/5edbb0d6-b8b1-4968-919e-516760675ec4)
![8-htvxSg2Xp8vjqV4](https://github.com/b0rn2my/MyPizzaSessionApp/assets/166199140/4fbdab16-d746-4b47-8c2f-2662fabfa57d)
![8-hws0vLJNRWaoSmx](https://github.com/b0rn2my/MyPizzaSessionApp/assets/166199140/e8818aff-d1fd-426e-9372-d1d611d3bf7a)
![8-kqECkz5NnJdLZz5](https://github.com/b0rn2my/MyPizzaSessionApp/assets/166199140/cdba78b9-f468-43db-9fcd-d416fa8171e5)
![8-mxW64TeaZYSSOXf](https://github.com/b0rn2my/MyPizzaSessionApp/assets/166199140/17250d3a-c557-4d74-a281-88f389a22e71)

**Comment by b0rn2my** [comment]
Das wird es oder was sagst du?

![image](https://github.com/b0rn2my/MyPizzaSessionApp/assets/101136546/efc98ff7-d566-4ffb-9f2d-2648468ee958)

**Comment by N0M3X** [comment]
Top :-)
