### ISSUE TITLE
"In den Warenkorb" Button sollte sich beim scrollen mitbewegen

### ISSUE THREAD

**Issue by N0M3X** [b0rn2my/MyPizzaSessionApp#20]
Der Button "In den Warenkorb" sollte sich beim scrollen und auswählen der Zutaten so mit bewegen das er am oberen Ende des Bildschirms fixiert wird. 
Da man meist von oben nach unten die Zutaten auswählt muss man Abschluss der Auswahl wieder komplett nach oben scrollen.

**Comment by b0rn2my** [comment]
Hier der Warenkorb Button aber natürlich alle Buttons.
Speichern use
