### ISSUE TITLE
Displaysperren verhindern beim abarbeiten von Bestellungen

### ISSUE THREAD

**Issue by b0rn2my** [b0rn2my/MyPizzaSessionApp#25]
https://dev.to/this-is-learning/how-to-prevent-the-screen-turn-off-after-a-while-in-blazor-4b29

**Comment by MatthiasUlrich1** [comment]
Das wäre wirklich hilfreich. Man muss sonst ständig wieder entsperren. Mit mehligen Händen ist das nicht so schön.

**Comment by b0rn2my** [comment]
@MatthiasUlrich1 
@N0M3X 

Sobald das Testsystem aktiv ist dies bitte testen.
Hier dann Rückmelden.

Vielen Dank

**Comment by b0rn2my** [comment]
iPhone als PWA funktioniert nicht. 
Bug von Apple

https://bugs.webkit.org/show_bug.cgi?id=254545#c32

[Bug](https://bugs.webkit.org/show_bug.cgi?id=254545#c32)
