### ISSUE TITLE
Mehrere Bestellungen pro Person/Session ermöglichen

### ISSUE THREAD

**Issue by N0M3X** [b0rn2my/MyPizzaSessionApp#26]
Es sollte möglich sein das eine Person mehrere Pizzen pro Session bestellt. 
Ich habe aktuell eine Session mit 7 Personen laufen -> 7 Bestellungen. Wenn allerdings nun eine Person 2 Pizzen bestellt steigt die Anzahl an Bestellungen um 1 und eine andere Person kann dadurch nicht mehr bestellen. Es sei denn ich setzt die Anzahl an Personen nach oben.

Oder habe ich hier einen Denkfehler?

**Comment by b0rn2my** [comment]
Nein die Anzahl der Personen wird x3 gerechnet. Danach kann man nicht mehr bestellen. 
Es kommt ein Hinweis ab Version 5.0.0 das zu viele Bestellungen eingegangen sind. 

Jeder kann gleichzeitig mehr bestellen. Du kannst N Pizzen in den Warenkorb packen und dann alle bestellen.

**Comment by N0M3X** [comment]
Und was ist wenn eine Person eine Pizza erstellt, in den Warenkorb legt und abschließt und danach nochmal das gleiche durchführt?

Bei mir stand bei 7 Personen zum Beispiel bei jeder neuen Pizza zum Beispiel 4/7 Bestellungen. Es müsste doch bei Faktor 3x 0/21 Bestellungen heißen.

**Comment by b0rn2my** [comment]
Stimmt da ist ein kleiner Denkfehler drin. Kann irreführend sein. 

Wenn er eine Bestellung abschickt dann kann er das gleiche nochmals machen. Jede Pizza wird als eigene Bestellung betrachtet. 

Die Anzeige Bestellungen sollte wirklich auch den Faktor beinhalten.
