### ISSUE TITLE
Seite Über MyPizzaSession

### ISSUE THREAD

**Issue by b0rn2my** [b0rn2my/MyPizzaSessionApp#40]
Seite für die Vorstellung der Seite. Mit Edit Funktion.

**Comment by b0rn2my** [comment]
![image](https://github.com/b0rn2my/MyPizzaSessionApp/assets/101136546/721523db-c34f-471f-a441-f591bbb6df7e)

**Comment by b0rn2my** [comment]
@N0M3X 
@TheTimoOfficial 

Darf ich euch auf der Seite erwähnen?
Wenn ja, bitte sagen mit welchem Namen. Gerne auch nur mit dem Username von Git.

**Comment by N0M3X** [comment]
@b0rn2my Gerne. Als Namen kannst du bei mir Jörg verwenden

**Comment by MatthiasUlrich1** [comment]
Gern darfst du meinen Namen nennen.

**Comment by b0rn2my** [comment]
Text einfügen

**Comment by b0rn2my** [comment]
Edit Seite falsch beschriftet 😃
![image](https://github.com/b0rn2my/MyPizzaSessionApp/assets/101136546/223b8054-b506-4a50-95e8-931c9fdcaea3)

**Comment by MatthiasUlrich1** [comment]
Hey ich erstelle gerade die Über Uns Seite.
Vielleicht könnt ihr @N0M3X @b0rn2my @TheTimoOfficial eine kurze Vorstellung von euch beisteuern. 

Ein Beispiel:

Matthias ist ein Technik-Enthusiast mit einer Leidenschaft für Smart Home-Technologie. Schon immer fasziniert von der Idee, sein Zuhause intelligenter und effizienter zu gestalten, hat er sich tief in die Welt der vernetzten Geräte eingearbeitet. Sein Zuhause ist sein persönliches Labor, in dem er ständig neue Technologien testet, integriert und programmiert, um den Alltag komfortabler und sicherer zu machen. 
Der Komfortgewinn von MyPizzaSession hat ihn begeistert und so hat er die App auf Herz und Nieren getestet, Zutaten-Vorlagen erstellt und neue Ideen eingebracht. 

Ich würde das dann in die Seite übernehmen. 

Gruß Matthias

**Comment by N0M3X** [comment]
Feuer, Glut und Geschmack sind seine Elemente. 
Jörg ist seit vielen Jahren ein leidenschaftlicher Hobbykoch. Vor allem das Kochen im Freien über offener Flamme hat es ihm angetan. Sei es im Dutch Oven, auf dem Grill oder im Pizzaofen. 
Als einer der ersten Nutzer von MyPizzaSession hat er schnell das Potential der App erkannt und bringt sich seitdem in allen Bereichen mit ein, um MyPizzaSession groß und erfolgreich zu machen.

**Comment by b0rn2my** [comment]
Über uns
Wir sind Pizza-Freunde wie du!
 
Was gibt es schöneres, als eine selbstgebackene Pizza mit der Familie, Freunden oder der Nachbarschaft zu teilen? Als echter Pizza-Liebhaber liebst du es bestimmt, deine Gäste mit immer neuen Kreationen zu begeistern und bei jeder Pizza-Session das Beste aus dir und deinem Ofen heraus zu holen.
Kennst du nicht auch das große Problem wenn deine Freunde am Tisch sitzen und sich nette Gespräche entwickelt haben, die du leider für die Frage der Pizza unterbrechen musst?
- Wer ist der nächste? 
- Was möchtest du auf deine Pizza?
- Was gibt es denn alles?
- Salami, Schinken usw.
- Möchtest du die Salami vor oder nach dem Backen auf die Pizza.
Wenn du diese Pizza fertig hast beginnt das Spiel wieder von Vorne. 
Wenn du also ein Hobby-Pizzabäcker bist auf den die obere Beschreibung zutrifft, bist du bei MyPizzaSession genau richtig, denn wir teilen deine Begeisterung für selbstgebackene Pizzen mit Familie, Freunden oder Nachbarn zu teilen.


Die Perfekt Pizza Session

Hier kaufst du, was du brauchst. 
Egal ob du den Geschmack deiner Gäste sehr gut kennst, der Einkauf ist immer wieder eine Herausforderung. Selten trifft man die Geschmäcker aller exact und kauft unnötig Zutaten ein. Wäre es nicht hilfreicher zuvor schon zu wissen in welche Richtung deine Gäste tendieren. 
Gerne kannst du zuvor jeden persönlich fragen aber wäre es nicht besser wenn deine Gäste in Ruhe entscheiden könnten. 
Hier bist du bei MyPizzaSession genau richtig, erstelle eine Session, pack alle Zutaten rein die du beschaffen könntest und sende die Einladung an deine Gäste.
Du kannst deinen Gästen die Entscheidung gerne mit erstellten Pizza Kreationen erleichtern. Probiere es gerne aus. 


Wie alles begann
 
Die Idee wurde von Tobias geboren, einem Pizza-Liebhaber seit 2021 und Kopf von My PizzaSession. Die Digitalisierung hat immer mehr Einfluss auf unser Leben, sie kann uns da Unterstützen wo wir es benötigen. Aus diesem Ansatz und den Antrieb was neues zu schaffen ist die Idee für eine Private App entstanden. Im Januar 2024 war es dann soweit, MyPizzaSession ging online. Schnell haben sich 3 weitere Mitstreiter von der Idee anstecken lassen und haben fleißig getestet und mit Ideen und Inhaltserstellung unterstützt und die App gemeinsam dahin entwickelt wo sie jetzt ist. Der Weg von MyPizzaSession ist nicht nicht zu Ende auch du kannst dich gerne einbringen. 




**und hier noch mein Abschnitt **
Tobias

Mein Name ist Tobias und ich bin leidenschaftlicher Programmierer. Schon seit meiner Kindheit fasziniert mich die Welt der Computer und ich verbringe jede freie Minute damit, neue Programme und Codes zu entwickeln. 

Neben dem Programmieren habe ich noch eine weitere Leidenschaft: die Welt der Pizza. Besonders gerne zaubere ich für meine Freunde und Familie napoletanische Pizza. Ich liebe es, den Teig selbst herzustellen, die frischen Zutaten darauf zu verteilen und die Pizza dann im heißen Ofen zu backen, bis sie knusprig und perfekt ist. 

Es macht mir einfach Freude, meine Liebsten mit meiner selbstgemachten Pizza zu verwöhnen und ihre strahlenden Gesichter zu sehen, wenn sie den ersten Bissen nehmen. Für mich ist das Backen nicht nur eine kulinarische Kunst, sondern auch eine Möglichkeit, meine Kreativität auszuleben und anderen eine Freude zu bereiten.

**Comment by b0rn2my** [comment]
@MatthiasUlrich1  sobald du den kompletten Text hast, hier bereit stellen.
Erstmals ohne Bilder da wir das neue Release brauchen.
Dieser Punkt muss fertig sein bis zum neuen Release.

**Comment by MatthiasUlrich1** [comment]
Über uns

Wir sind Pizza-Freunde wie du!

 

Was gibt es schöneres, als eine selbstgebackene Pizza mit der Familie, Freunden oder der Nachbarschaft zu teilen? Als echter Pizza-Liebhaber liebst du es bestimmt, deine Gäste mit immer neuen Kreationen zu begeistern und bei jeder Pizza-Session das Beste aus dir und deinem Ofen heraus zu holen.

Kennst du nicht auch das große Problem wenn deine Gäste am Tisch sitzen und sich nette Gespräche entwickelt haben, die du leider für die Frage der Pizza unterbrechen musst?

    Wer ist der nächste?
    Was möchtest du auf deine Pizza?
    Was gibt es denn alles?
    Salami, Schinken usw.
    Möchtest du die Salami vor oder nach dem Backen auf die Pizza?

Wenn du diese Pizza fertig hast beginnt das Spiel mit dem nächsten Gast von Vorne.

Wenn du also ein Hobby-Pizzabäcker bist auf den die obere Beschreibung zutrifft, bist du bei der innovativen Plattform MyPizzaSession genau richtig, denn wir teilen deine Begeisterung für selbstgebackene Pizzen mit Familie, Freunden oder Nachbarn zu genießen.

Die Perfekt Pizza Session

Hier kaufst du, was du brauchst.

Egal ob du den Geschmack deiner Gäste sehr gut kennst, der Einkauf ist immer wieder eine Herausforderung. Selten trifft man die Geschmäcker aller exact und kauft unnötig Zutaten ein. Wäre es nicht hilfreicher zuvor schon zu wissen in welche Richtung deine Gäste tendieren?

Sicher könnte man zuvor jeden persönlich fragen aber wäre es nicht besser wenn deine Gäste in Ruhe entscheiden könnten, egal ob spät abends oder früh morgens.

Hier bist du bei MyPizzaSession genau richtig, erstelle eine Session, pack alle Zutaten rein die du beschaffen könntest und sende die Einladung an deine Gäste.

Du kannst deinen Gästen die Entscheidung gerne mit erstellten Pizza Kreationen erleichtern. Probiere es gerne aus.

Unser Antrieb

Die Verschwendung von Lebensmitteln ist in der heutigen Zeit mit hohen Kosten verbunden. Durch die Erhaltenen Bestellungen kannst du deinen Einkauf so effizient wie möglich gestalten. Das Internet ist heut zu Tage nicht mehr weg zu denken. Es hilft uns gewisse Aufgaben zu erledigen und erleichtert uns das Leben. Wir wollen dies auch beim Pizza backen nutzen um alle Vorteile der Digitalisierung zu erhalten.

Wie alles begann

 

Die Idee wurde von Tobias geboren, einem Pizza-Liebhaber seit 2021 und Kopf von My PizzaSession. Die Digitalisierung hat immer mehr Einfluss auf unser Leben, sie kann uns da Unterstützen wo wir es benötigen. Aus diesem Ansatz und den Antrieb was neues zu schaffen ist die Idee für eine Private App entstanden. Im Januar 2024 war es dann soweit, MyPizzaSession ging online. Schnell haben sich 3 weitere Mitstreiter von der Idee anstecken lassen und haben fleißig getestet und mit Ideen und Inhaltserstellung unterstützt und die App gemeinsam dahin entwickelt wo sie jetzt ist. Der Weg von MyPizzaSession ist nicht nicht zu Ende auch du kannst dich gerne einbringen.


Hier wollen wir uns kurz vorstellen.



Tobias:

Mein Name ist Tobias und ich bin leidenschaftlicher Programmierer. Schon seit meiner Kindheit fasziniert mich die Welt der Computer und ich verbringe jede freie Minute damit, neue Programme und Codes zu entwickeln.

Neben dem Programmieren habe ich noch eine weitere Leidenschaft: die Welt der Pizza. Besonders gerne zaubere ich für meine Freunde und Familie napoletanische Pizza. Ich liebe es, den Teig selbst herzustellen, die frischen Zutaten darauf zu verteilen und die Pizza dann im heißen Ofen zu backen, bis sie knusprig und perfekt ist.

Es macht mir einfach Freude, meine Liebsten mit meiner selbstgemachten Pizza zu verwöhnen und ihre strahlenden Gesichter zu sehen, wenn sie den ersten Bissen nehmen. Für mich ist das Backen nicht nur eine kulinarische Kunst, sondern auch eine Möglichkeit, meine Kreativität auszuleben und anderen eine Freude zu bereiten.




Matthias:

Ich bin Matthias, ein Technik-Enthusiast mit einer Leidenschaft für Smart Home-Technologie. Schon immer fasziniert von der Idee, sein Zuhause intelligenter und effizienter zu gestalten, habe ich mich tief in die Welt der vernetzten Geräte eingearbeitet. Mein Zuhause ist mein persönliches Labor, in dem ich ständig neue Technologien teste, integriere und programmiere, um meinen Alltag komfortabler und sicherer zu machen. Wie ein das Smart Home das Zuhause vernetzt, verbindet Pizza Menschen überall auf der Welt.

Der Komfortgewinn von MyPizzaSession hat mich sofort begeistert und so habe ich die App auf Herz und Nieren getestet, Zutaten-Vorlagen erstellt und neue Ideen eingebracht. 

MyPizzaSession macht die Organisation leicht und es bleibt mehr Zeit für gute Gespräche.


Jörg:

Feuer, Glut und Geschmack sind seine Elemente.

Jörg ist seit vielen Jahren ein leidenschaftlicher Hobbykoch. Vor allem das Kochen im Freien über offener Flamme hat es ihm angetan. Sei es im Dutch Oven, auf dem Grill oder im Pizzaofen.

Als einer der ersten Nutzer von MyPizzaSession hat er schnell das Potential der App erkannt und bringt sich seitdem in allen Bereichen mit ein, um MyPizzaSession groß und erfolgreich zu machen.



Unsere Vision:

Gemeinsam haben wir es uns zur Aufgabe gemacht, die Organisation von Pizzaabenden so einfach und unterhaltsam wie möglich zu gestalten. Wir sind leidenschaftliche Pizza-Liebhaber und möchten, dass jeder Pizzaabend ein voller Erfolg wird. Probiere es aus und lass uns gemeinsam den perfekten Pizzaparty-Abend kreieren!

**Comment by MatthiasUlrich1** [comment]
About Us


We are pizza friends like you!




What could be nicer than sharing a home-made pizza with family, friends or the neighborhood? As a real pizza lover, you probably love to delight your guests with new creations and get the most out of you and your oven at every pizza session.


Don't you know the big problem when your guests are sitting at the table and have had nice conversations that you unfortunately have to interrupt to ask about the pizza?


    Who's next?

    What would you like on your pizza?

    What is there?

    Salami, ham, etc.

    Would you like the salami on the pizza before or after baking?


When you have finished this pizza the game starts over with the next guest.


So if you are a hobby pizza maker who fits the description above, you have come to the right place with the innovative platform MyPizzaSession, because we share your enthusiasm for enjoying homemade pizzas with family, friends or neighbors.


The perfect pizza session


Here you buy what you need.


No matter whether you know your guests' tastes very well, purchasing is always a challenge. You rarely meet everyone's tastes exactly and buy ingredients unnecessarily. Wouldn't it be more helpful to know in advance which direction your guests tend to go?


Of course you could ask everyone personally beforehand, but wouldn't it be better if your guests could decide in peace, whether late in the evening or early in the morning.


MyPizzaSession is the right place for you. Create a session, put in all the ingredients you could get and send the invitation to your guests.


You can make the decision easier for your guests with pizza creations you have created. Feel free to try it out.


Our drive


Wasting food these days is associated with high costs. By receiving orders you can make your shopping as efficient as possible. These days it is impossible to imagine life without the Internet. It helps us complete certain tasks and makes our lives easier. We also want to use this when baking pizza to get all the benefits of digitalization.


How it all began




The idea was born by Tobias, a pizza lover since 2021 and head of My PizzaSession. Digitalization is having more and more influence on our lives; it can support us where we need it. The idea for a private app emerged from this approach and the drive to create something new. In January 2024 the time had come and MyPizzaSession went online. Three other colleagues quickly became infected with the idea and diligently tested and supported with ideas and content creation and developed the app together to where it is now. The journey of MyPizzaSession is not over, you are welcome to get involved.



Here we would like to briefly introduce ourselves.




Tobias:


My name is Tobias and I am a passionate programmer. The world of computers has fascinated me since I was a child and I spend every free minute developing new programs and codes.


In addition to programming, I have another passion: the world of pizza. I particularly enjoy making Neapolitan pizza for my friends and family. I love making the dough myself, spreading the fresh ingredients on top, and then baking the pizza in the hot oven until it's crispy and perfect.


I simply enjoy treating my loved ones to my homemade pizza and seeing their smiles on their faces when they take the first bite. For me, baking is not only a culinary art, but also a way to express my creativity and bring joy to others.





Matthias:


I'm Matthias, a technology enthusiast with a passion for smart home technology. Always fascinated by the idea of making your home smarter and more efficient, I delved deeply into the world of connected devices. My home is my personal laboratory where I constantly test, integrate and program new technologies to make my everyday life more comfortable and safer. Just as the smart home connects the home, pizza connects people all over the world.


I was immediately impressed by the increased convenience of MyPizzaSession and so I put the app through its paces, created ingredient templates and introduced new ideas.


MyPizzaSession makes organization easy and there is more time for good conversations.



Jörg:


Fire, embers and taste are its elements.


Jörg has been a passionate hobby cook for many years. He particularly enjoys cooking outdoors over an open flame. Be it in the Dutch oven, on the grill or in the pizza oven.


As one of the first users of MyPizzaSession, he quickly recognized the app's potential and has been using it ever since

**Comment by b0rn2my** [comment]
Perfekt, ich mache das so rein. 
Erstmals ohne Bilder. Vielen Dank

**Comment by MatthiasUlrich1** [comment]
Im Testsystem hab ich es schon eingefügt.

**Comment by N0M3X** [comment]
"sich 3 weitere Mitstreiter"

Fehlt hier nicht noch jemand?

**Comment by MatthiasUlrich1** [comment]
Ja @TheTimoOfficial fehlt noch.

**Comment by b0rn2my** [comment]
Über uns

Wir sind Pizza-Freunde wie du!

 

Was gibt es schöneres, als eine selbstgebackene Pizza mit der Familie, Freunden oder der Nachbarschaft zu teilen? Als echter Pizza-Liebhaber liebst du es bestimmt, deine Gäste mit immer neuen Kreationen zu begeistern und bei jeder Pizza-Session das Beste aus dir und deinem Ofen heraus zu holen.

Kennst du nicht auch das große Problem wenn deine Gäste am Tisch sitzen und sich nette Gespräche entwickelt haben, die du leider für die Frage der Pizza unterbrechen musst?

Wer ist der nächste?
Was möchtest du auf deine Pizza?
Was gibt es denn alles?
Salami, Schinken usw.
Möchtest du die Salami vor oder nach dem Backen auf die Pizza?
Wenn du diese Pizza fertig hast beginnt das Spiel mit dem nächsten Gast von Vorne.

Wenn du also ein Hobby-Pizzabäcker bist auf den die obere Beschreibung zutrifft, bist du bei der innovativen Plattform MyPizzaSession genau richtig, denn wir teilen deine Begeisterung für selbstgebackene Pizzen mit Familie, Freunden oder Nachbarn zu genießen.

Die Perfekt Pizza Session

Hier kaufst du, was du brauchst.

Egal ob du den Geschmack deiner Gäste sehr gut kennst, der Einkauf ist immer wieder eine Herausforderung. Selten trifft man die Geschmäcker aller exact und kauft unnötig Zutaten ein. Wäre es nicht hilfreicher zuvor schon zu wissen in welche Richtung deine Gäste tendieren?

Sicher könnte man zuvor jeden persönlich fragen aber wäre es nicht besser wenn deine Gäste in Ruhe entscheiden könnten, egal ob spät abends oder früh morgens.

Hier bist du bei MyPizzaSession genau richtig, erstelle eine Session, pack alle Zutaten rein die du beschaffen könntest und sende die Einladung an deine Gäste.

Du kannst deinen Gästen die Entscheidung gerne mit erstellten Pizza Kreationen erleichtern. Probiere es gerne aus.

Unser Antrieb

Die Verschwendung von Lebensmitteln ist in der heutigen Zeit mit hohen Kosten verbunden. Durch die Erhaltenen Bestellungen kannst du deinen Einkauf so effizient wie möglich gestalten. Das Internet ist heut zu Tage nicht mehr weg zu denken. Es hilft uns gewisse Aufgaben zu erledigen und erleichtert uns das Leben. Wir wollen dies auch beim Pizza backen nutzen um alle Vorteile der Digitalisierung zu erhalten.

Wie alles begann

 

Die Idee wurde von Tobias geboren, einem Pizza-Liebhaber seit 2021 und Kopf von My PizzaSession. Die Digitalisierung hat immer mehr Einfluss auf unser Leben, sie kann uns da Unterstützen wo wir es benötigen. Aus diesem Ansatz und den Antrieb was neues zu schaffen ist die Idee für eine Private App entstanden. Im Januar 2024 war es dann soweit, MyPizzaSession ging online. Schnell haben sich 3 weitere Mitstreiter von der Idee anstecken lassen und haben fleißig getestet und mit Ideen und Inhaltserstellung unterstützt und die App gemeinsam dahin entwickelt wo sie jetzt ist. Der Weg von MyPizzaSession ist nicht nicht zu Ende auch du kannst dich gerne einbringen.



Hier wollen wir uns kurz vorstellen.





Tobias:

Mein Name ist Tobias und ich bin leidenschaftlicher Programmierer. Schon seit meiner Kindheit fasziniert mich die Welt der Computer und ich verbringe jede freie Minute damit, neue Programme und Codes zu entwickeln.

Neben dem Programmieren habe ich noch eine weitere Leidenschaft: die Welt der Pizza. Besonders gerne zaubere ich für meine Freunde und Familie napoletanische Pizza. Ich liebe es, den Teig selbst herzustellen, die frischen Zutaten darauf zu verteilen und die Pizza dann im heißen Ofen zu backen, bis sie knusprig und perfekt ist.

Es macht mir einfach Freude, meine Liebsten mit meiner selbstgemachten Pizza zu verwöhnen und ihre strahlenden Gesichter zu sehen, wenn sie den ersten Bissen nehmen. Für mich ist das Backen nicht nur eine kulinarische Kunst, sondern auch eine Möglichkeit, meine Kreativität auszuleben und anderen eine Freude zu bereiten.







Matthias:

Ich bin Matthias, ein Technik-Enthusiast mit einer Leidenschaft für Smart Home-Technologie. Schon immer fasziniert von der Idee, sein Zuhause intelligenter und effizienter zu gestalten, habe ich mich tief in die Welt der vernetzten Geräte eingearbeitet. Mein Zuhause ist mein persönliches Labor, in dem ich ständig neue Technologien teste, integriere und programmiere, um meinen Alltag komfortabler und sicherer zu machen. Wie ein das Smart Home das Zuhause vernetzt, verbindet Pizza Menschen überall auf der Welt.

Der Komfortgewinn von MyPizzaSession hat mich sofort begeistert und so habe ich die App auf Herz und Nieren getestet, Zutaten-Vorlagen erstellt und neue Ideen eingebracht. 

MyPizzaSession macht die Organisation leicht und es bleibt mehr Zeit für gute Gespräche.



Jörg:

Feuer, Glut und Geschmack sind seine Elemente.

Jörg ist seit vielen Jahren ein leidenschaftlicher Hobbykoch. Vor allem das Kochen im Freien über offener Flamme hat es ihm angetan. Sei es im Dutch Oven, auf dem Grill oder im Pizzaofen.

Als einer der ersten Nutzer von MyPizzaSession hat er schnell das Potential der App erkannt und bringt sich seitdem in allen Bereichen mit ein, um MyPizzaSession groß und erfolgreich zu machen.





Unsere Vision:

Gemeinsam haben wir es uns zur Aufgabe gemacht, die Organisation von Pizzaabenden so einfach und unterhaltsam wie möglich zu gestalten. Wir sind leidenschaftliche Pizza-Liebhaber und möchten, dass jeder Pizzaabend ein voller Erfolg wird. Probiere es aus und lass uns gemeinsam den perfekten Pizzaparty-Abend kreieren!

**Comment by b0rn2my** [comment]
Hallo zusammen, 
About Us Page ist soweit fertig ich habe hier nun noch 5 Bilder offen die wir einbauen können.

Von den 5 Bildern sind 3 unsere und zwei Globale. 
Wer kein Bild von sich veröffentlichen will kann auch gerne eine Avatar verwenden. Könntet ihr mir diese zukommen lassen.

Habt ihr für die anderen beiden Bilder irgend welche Ideen?

**Comment by N0M3X** [comment]
Hi,

anbei mein Bild. Soll ich mal schauen was die KI für die zwei Globalen ausspuckt? Eventuell etwas Italienisch angehauchtes?

![1](https://github.com/b0rn2my/MyPizzaSessionApp/assets/166199140/4f7e67f8-7a50-4ab6-9e41-317e95e1675a)

**Comment by N0M3X** [comment]
Habe hier mal einige Bilder für die "Über Uns" Seite erstellt. Ist was dabei was euch gefällt? Wenn ja welcher Stil? ACHTUNG: Die Bilder sind noch nicht kommerziell. Wenn wir uns auf einen Stil geeinigt haben kann ich weitere Bilder für die kommerzielle Nutzung erstellen.

![1](https://github.com/b0rn2my/MyPizzaSessionApp/assets/166199140/a01edebc-1b78-4617-af16-3e41d628c3c8)
![2](https://github.com/b0rn2my/MyPizzaSessionApp/assets/166199140/413c721a-3c57-4397-8588-c9430c03b16f)
![3](https://github.com/b0rn2my/MyPizzaSessionApp/assets/166199140/2fca3dc3-05bc-48b8-848f-c5730cb098ea)
![4](https://github.com/b0rn2my/MyPizzaSessionApp/assets/166199140/4617a18c-a65a-45be-a9b6-c860eda2f50d)
![5](https://github.com/b0rn2my/MyPizzaSessionApp/assets/166199140/1e3d9bb4-4cc0-4d4c-94bc-71604af1048e)
![6](https://github.com/b0rn2my/MyPizzaSessionApp/assets/166199140/7cc4d31b-1b85-418a-b987-4e6e1d9fc185)

**Comment by MatthiasUlrich1** [comment]
![IMG_2694](https://github.com/b0rn2my/MyPizzaSessionApp/assets/103759633/11e7ab51-18e3-414a-99bc-dcb90a601be9)


Hier ein Bild von mir,

Die Globalen Bilder der KI Nr 4 und 5 find ich am besten, leider haben alle das gleiche Gesicht 😅

**Comment by N0M3X** [comment]
Ja das sind leider die Tücken der KI ;-)

**Comment by b0rn2my** [comment]
Hab jetzt mal Bild 5 für das Testsystem benutzt

**Comment by b0rn2my** [comment]
Bitte im Testsystem prüfen wenn es online ist. Informiere in WhatsApp

**Comment by N0M3X** [comment]
Habe jetzt mal drei Bilder mit kommerziellen Rechten erstellt. Was haltet Ihr davon?

![1](https://github.com/b0rn2my/MyPizzaSessionApp/assets/166199140/9bf35cd7-e801-47a1-a3ff-f56b16b71ca6)
![2](https://github.com/b0rn2my/MyPizzaSessionApp/assets/166199140/037c18d4-cf96-4645-b112-534e65df558e)
![3](https://github.com/b0rn2my/MyPizzaSessionApp/assets/166199140/98254e21-b776-44a7-8fa3-69c34e2d38e1)

**Comment by b0rn2my** [comment]
Bereit zum testen
