### ISSUE TITLE
Rubrik "Vegetarisch" in "Obst" und "Gemüse" trennen

### ISSUE THREAD

**Issue by N0M3X** [b0rn2my/MyPizzaSessionApp#46]

**Comment by b0rn2my** [comment]
Die Reihenfolge der Gruppen wird:

Soße
Käse
Fleisch
Fisch
Gemüse
Obst
Süßes

Passt das?

**Comment by N0M3X** [comment]
Lässt du "verfeinern" nicht drin? Würde das vor süßes packen

**Comment by b0rn2my** [comment]
Bleibt natürlich😉
