### ISSUE TITLE
Pizza Gruppieren

### ISSUE THREAD

**Issue by b0rn2my** [b0rn2my/MyPizzaSessionApp#48]
Ähnlich wie Zutaten
- Vegetarisch
- Fleisch
- Fisch
- Nachspeise 

evtl hier auch Calzone

**Comment by b0rn2my** [comment]
@N0M3X 
Noch eine Idee für mögliche Gruppen?

**Comment by N0M3X** [comment]
Vegan
Vorspeisen (Pizzabrot, Mini Pizza)

Eventuell noch die Einteilung nach Pizza Tonda (römische Art), Neapolitana oder American Style

**Comment by b0rn2my** [comment]
Ist jetzt die Frage ob wir es mit der Art mischen? Eigentlich nicht sonst hat man ja die anderen Gruppen wieder gemischt in der Gruppe der Art

**Comment by N0M3X** [comment]
Ja stimmt auch wieder. Eventuell kann man den "Typ" (Tonda, Neapolitana, American) schon irgendwo bei der Bestellung mit einbauen, sodass ich als Gast sehe welchen Typ von Pizza meine Gäste haben wollen.

**Comment by b0rn2my** [comment]
Das ist noch ein offener Punkt den ich sicher noch mache. Ist leider in der Prio nicht an erster Stelle.

**Comment by b0rn2my** [comment]
Also kommen die Gruppen:

Vorspeise
Fleisch
Fisch
Vegetarisch
Vegan
Nachspeise

**Comment by N0M3X** [comment]
Perfekt :-)

**Comment by MatthiasUlrich1** [comment]
Hawaai sollte eine eigene Kategorie sein ;-) 
SPaß bei Seite. Die Kategorien passen so...
