### ISSUE TITLE
Button zur Einkaufsliste führt immer zur ersten Session. 

### ISSUE THREAD

**Issue by MatthiasUlrich1** [b0rn2my/MyPizzaSessionApp#53]
Die Einkaufsliste von Session test kann nicht angewählt werden.

**Comment by b0rn2my** [comment]
Es ging nicht um die Einkaufsliste sondern um die Bestellseite der Session.
Es wählte immer die aktuelle Session aus obwohl ein Link übergeben wurde.
Problem wurde behoben.
