### ISSUE TITLE
Mehrere Pizzas in einer Bestellung / Namen nicht löschen

### ISSUE THREAD

**Issue by b0rn2my** [b0rn2my/MyPizzaSessionApp#59]
![image](https://github.com/b0rn2my/MyPizzaSessionApp/assets/101136546/fbeb3e70-374a-4535-b02a-ce032f90cb98)

**Comment by b0rn2my** [comment]
@N0M3X also ich finde die Anforderung unnötig und macht es nur kompliziert. Zutaten zu Pizza eins, zwei oder 3 hinzufügen?????

Ebenfalls kann der Warenkorb dies.

**Comment by N0M3X** [comment]
Dem User geht's darum das man nicht immer den Namen erneut eingeben muss oder? Hab's grad mal im Testsystem ausprobiert. Würde das jetzt auch nicht ändern. Wir machen's immer so wenn jemand von uns zwei oder mehr Pizzen haben will schreib er halt Markus 1 und Markus 2. So weiß ich auch gleich welche ich zu beginn machen soll.

**Comment by b0rn2my** [comment]
Bin ich auch der Meinung das einzige was ich wirklich überlege ist ob der Name stehen bleiben soll wenn man eine Bestellung in den Warenkorb legt.
Diesen würde ich aber nicht in den Cookies speichern sondern beim neu laden der Seite leer lassen.

Was hältst du davon?

**Comment by N0M3X** [comment]
Ja das wäre eine gute Möglichkeit ohne die Bestellseite noch mehr zu überladen
