### ISSUE TITLE
Zutaten Alphabetisch Ordnen

### ISSUE THREAD

**Issue by b0rn2my** [b0rn2my/MyPizzaSessionApp#62]
Anpassung in folgenden Seiten
- Zutaten Vorlagen
- Vorlagen hinzufügen
- Zutaten Übersicht.
- Pizza Zutaten
- Pizza erstellen
- Bestellseite

**Comment by N0M3X** [comment]
Sollte erledigt sein wenn ich richtig gesehen habe, oder?

**Comment by b0rn2my** [comment]
Nein, da habe ich nichts gemacht. Dachte mir das hatte ich von Anfang an. Geprüft habe ich das aber noch nicht.

**Comment by b0rn2my** [comment]
Habe gerade nach gesehen. 
Bei den Vorlagen fehlt die alphabetische Anordnung.

**Comment by N0M3X** [comment]
Ok, hab nur bei den Zutaten selbst geschaut.
