### ISSUE TITLE
Einkaufsliste und Einladungsemail trennen

### ISSUE THREAD

**Issue by b0rn2my** [b0rn2my/MyPizzaSessionApp#63]

**Comment by N0M3X** [comment]
Zusatz: Eventuell auch noch das Layout an sich der Einladungs-, und Einkaufslisten Email überarbeiten.

**Comment by N0M3X** [comment]
@b0rn2my: Soll ich hier mal schauen wie dir die Einladungsmail und Einkaufslisten Mail optisch gestalten und organisieren können?

**Comment by b0rn2my** [comment]
Ja bitte

**Comment by N0M3X** [comment]
1. Das Wichtigste wäre zu Beginn die Trennung der beiden Emails (vorerst im Testsystem) sodass wir Testen können.
2. Zutaten welche nicht gewählt wurden, würde ich in der Einkaufsliste ausblenden

**Comment by b0rn2my** [comment]
In der E-Mail wird es mit ausblenden Schwierig. 
Gmail mag z.B. viele css styles nicht. 

Du kannst ja mal eine Vorlage in Word erstellen, inklusive Farben Hintergrund usw. 
Was hältst du davon?

Gruß Tobias

**Comment by N0M3X** [comment]
Ja gute Idee, schick dir nächste Woche mal zwei Vorlagen durch

**Comment by N0M3X** [comment]
Anbei die Änderungen an den Emails:

[Emails.docx](https://github.com/user-attachments/files/15971362/Emails.docx)

**Comment by b0rn2my** [comment]
Sieht super aus. Ich werde die Faben an die Seite anpassen. Hoffe das ich das mit GMail hin bekomme

**Comment by b0rn2my** [comment]
@N0M3X 

Einladungsemail:


![Image](https://github.com/b0rn2my/MyPizzaSessionApp/assets/101136546/15164d81-a781-46c0-8a2e-365dac1d6cab)


Passt das so?

**Comment by N0M3X** [comment]
Perfekt. Würde nur eine andere Schriftart wählen. Die sieht so kindlich aus ;-)
Und kann man den QR an den Ecken abrunden? Finde das würde hochwertiger aussehen.

**Comment by b0rn2my** [comment]
So?

![Image](https://github.com/b0rn2my/MyPizzaSessionApp/assets/101136546/651cba92-0094-4471-a547-ef29de3bad19)



![Image](https://github.com/b0rn2my/MyPizzaSessionApp/assets/101136546/052ad400-6a60-4539-9b94-16ca54a2eb30)

**Comment by b0rn2my** [comment]
QR-Code

![Image](https://github.com/b0rn2my/MyPizzaSessionApp/assets/101136546/18bf4a1a-f53c-4216-899e-3bfa8cbde1f5)

**Comment by N0M3X** [comment]
Perfekt :-)
