### ISSUE TITLE
Änderungen/Ideen für Version 5.0.0

### ISSUE THREAD

**Issue by N0M3X** [b0rn2my/MyPizzaSessionApp#7]
**Startseite // Änderung // „auf der“ -> „“zur“**
"Herzlich Willkommen auf der weltweit ersten Pizza-Session App" ändern in "Herzlich Willkommen zur weltweit ersten Pizza-Session App"

**Meine Zutaten // Änderung // „Grundbelag“ -> „Saucen“**
Eventuell sollte man die Rubrik Grundbelag in Saucen ändern, was meinst du?

**Meine Zutaten // Änderung // Käse nach Grundbelag/Saucen anordnen**
Ich würde die Rubrik Käse direkt nach oben unter Grundbelag/Saucen setzen, da dies meistens die 2. Zutat ist.

**Meine Sessions // Änderung // Vorlaufzeit Tag verlängern**
Wie besprochen eventuell die Vorlaufzeit auf 4 Wochen erhöhen

**Meine Sessions // Änderung // Pizza löschen -> RSF -> entfärnen**
Rechtschreibfehler beim Löschen einer Pizza

**Meine Sessions // Änderung // Pizza löschen -> „auf denen“ -> „bei denen“**
Rechtschreibfehler beim Löschen einer Pizza

**Meine Sessions // Änderung // RSF -> Pizza Session bearebiten**
Rechtschreibfehler beim "Gelben Stift" 

**Bestellung/Warenkorb // RSF -> noch -> Noch**
Rechtschreibfehler beim hinzufügen von Bestellungen zum Warenkorb
	
**Einkaufsliste // Änderung // Mengenangaben**
Was hältst du davon in der Einkaufsliste Mengenangaben mit anzugeben? Sprich 2 Leute bestellen Pizza Schinken (Tomatensauce, Mozzarella, Schinken) dann wird in der Einkaufsliste nicht nur Schinken 2, Mozzarella 2, Tomatensauce 2 angezeigt sondern zum Beispiel Schinken 200g, Tomatensauce 100g, Mozzarella 200g. Dafür müsste man deklarieren welche Menge pro Pizza pro Zutat veranschlagt wird.

**Bestellung abarbeiten // Popupfenster // RSF -> ist fertig**
Rechtschreibfehler beim fertigstellen einer Pizza. "Nicht Pizza für ... fertig" sondern "Pizza für ... ist fertig".

**Comment by b0rn2my** [comment]
#15
