### ISSUE TITLE
Kennzeichnung bei Extrawünschen

### ISSUE THREAD

**Issue by N0M3X** [b0rn2my/MyPizzaSessionApp#78]
In der Bestellübersicht sollte eine Markierung (Rotes Ausrufezeichen, Blitz, ...) angezeigt werden, wenn der Kunde das Feld "Extrawünsche" beschriftet hat.

So geht nichts unter.

**Comment by b0rn2my** [comment]
Servus,
ich finde bei Darstellung auf einem Handy keinen Platz dafür.
Wird schwierig....
Möchte die Übersicht der Zutaten nicht raus nehmen.

Datum wäre noch das was man wohl weg lassen könnte....

**Comment by N0M3X** [comment]
Wie wäre es wenn du den Extrawunsch vor den Zutaten (beim Aufklappen) mit anzeigst? Siehe Bild (roter Kreis).
![1](https://github.com/user-attachments/assets/e4ea0db9-ed0f-4cec-86aa-856e9fed9b15)

**Comment by b0rn2my** [comment]
Hallo Jörg,
an das habe ich auch schon gedacht. Ist dann aber auch nicht auf den ersten Blick sichtbar. 
Wollte eigentlich ein Info Icon hin machen mit Popover drauf. Leider fehlt da ein wenig der Platz. 
Wie gesagt entweder in die Liste beim aufklappen oder das Datum weg. 

Was meinst du?

**Comment by N0M3X** [comment]
Dann würde ich lieber das Datum entfernen. Habe da bisher noch nie drauf geachtet. Die Bestellungen kann man ja trotzdem chronologisch nach Bestelleingang sortieren.

**Comment by b0rn2my** [comment]
Passt für mich. 

Bestellungsübersicht:
- Datum entfernen. 
- Info wenn extrawunsch mit Icon
- Popover mit Inhalt.

**Comment by N0M3X** [comment]
Hört sich gut an. Aber was meinst du mit popover mit Inhalt?

**Comment by b0rn2my** [comment]
Ein Button wo ein Hinweis sich über die Seite legt. 

![image](https://github.com/user-attachments/assets/125a4f45-58cc-43b5-a2f2-de4d7d92f009)
