### ISSUE TITLE
Bilder mittels "https://hotpot.ai/art-generator" erstellen

### ISSUE THREAD

**Issue by N0M3X** [b0rn2my/MyPizzaSessionApp#8]
Ich habe einen Premium Zugang zu "https://hotpot.ai/art-generator". Das bedeutet die somit erstellten Bilder können kommerziell genutzt werden. Damit könnten wir die Bilder für das Titelbild oder die Zutaten erstellen und hätten somit einheitliche Bilder.

**Siehe FAQ**

Can I use Hotpot graphics and text commercially?

Yes, if you buy credits or buy a license.

Note this only authorizes you to use Hotpot for commercial reasons.

This does not constitute copyright or intellectual property protection. We cannot guarantee uniquess anymore than Photoshop or Microsoft Word. It is conceivable for someone to produce similar or even identical content with other software or AI. This means any logo, text, or graphic produced on Hotpot could be made elsewhere.

Treat Hotpot as an AI helper who sparks creativity and automates drudgery -- but not someone who verifies compliance with intellectual property laws.

Ultimately, Hotpot is nothing but a general tool that produces graphics and text guided by a human.

It is your responsibility to produce unique content that honors local and international laws. To personalize graphics more easily, use unique seed images with [AI Art Generator](https://hotpot.ai/art-generator) or [AI Art Remixer](https://hotpot.ai/personalize-art).

We may use invisible watermarks to identify Hotpot creations for legal disputes.

**Comment by b0rn2my** [comment]
Hört sich sehr gut an. Hast du da bei Premium alles frei oder nur eine gewisse Anzahl?
Du könntest mal zwei, drei Bilder erstellen wie du sie dir vorstellst und hier dann mal einfügen. 
Kann mir jetzt nicht viel darunter vorstellen. Die KI die ich mal getestet habe war nicht sehr gut da war schon viel dabei was unbrauchbar war.

**Comment by b0rn2my** [comment]
Sehen nicht schlecht aus. 
Aber denke auch wie du gesagt hast das einheitlich Bilder am Schluss das Beste sind. 
Kannst du die Bilder deiner Zutaten auch mit Farbe erstellen?

**Comment by N0M3X** [comment]
Hab die Bilder von mir auch nur von ner Pix Seite. Leider ohne Urheberrecht daher kann ich sie nur privat nutzen. Kennst du Fiverr? Des wär auch noch ne Option

**Comment by N0M3X** [comment]
Übersicht Zutaten:

Tomatensauce
Sahnesauce!
Burrata
Camembert
Gorgonzola
Mozzarella
Parmesan
Schafskäse
Mortadella
Parmaschinken
Salami
Schinken
Speck
Würstchen
Garnelen
Sardellen
Thunfisch
Ananas
Avocado
Birne
Champignons
Ei
Erbsen
Kapern
Kirschtomaten
Mais
Oliven
Paprika
Peperoni
Rucola
Spinat
Zwiebeln
Basilikum
Chili
Chiliöl
Knoblauch
Oregano
Pesto
Pinienkerne
Banane!
Nutella!

**Comment by b0rn2my** [comment]
Pesto würde ich aufteilen
Ist aber dann nur ein Bild für grünes Pesto und eines für rotes. 

- Basilikum Pesto
- Bärlauch Pesto
- Pistazien Basilikum Pesto

Rotes Pesto
- Pesto Calabrese
- Tomaten Pesto

**Comment by N0M3X** [comment]
Top 👍🏻 Wie sollen die Grafiken werden? Was hältst du von der Grafik aus meinem Account? Hätte sie wieder mit hotpot (kommerziell) erstellt.

**Comment by b0rn2my** [comment]
Punkt ist ja nun erledigt, ich schließe
