### ISSUE TITLE
Optische Änderungen

### ISSUE THREAD

**Issue by N0M3X** [b0rn2my/MyPizzaSessionApp#87]
- Session Name neben "Session:" platzieren.

- Extrawünsche werden nicht im Warenkorb angezeigt

![image](https://github.com/user-attachments/assets/a59c5762-ecb3-4f62-92f7-c6857dd5f731)

**Comment by N0M3X** [comment]
"What's new" umbenennen in "Was gibt es Neues" oder "Neuigkeiten"

![image](https://github.com/user-attachments/assets/b90da44e-935e-4600-84fd-d0cda99de6f2)

**Comment by N0M3X** [comment]
Umbenennen von "Kontaktformular" in "Kontakt"

![image](https://github.com/user-attachments/assets/76561b92-c2c3-4ff4-9689-628ae43ace4b)

**Comment by N0M3X** [comment]
Test 
für Jörg 2

bessere Darstellung:

Nur der Bestellername. Beispiel von oben:

Jörg 2

![image](https://github.com/user-attachments/assets/6c2bd517-eed9-4d13-9ddd-4f9cf153366b)

**Comment by N0M3X** [comment]
Zusammenfassen zu einer Seite -> "Partner"

![image](https://github.com/user-attachments/assets/9fb74089-feb4-475d-a437-49bead44aaf2)

**Comment by N0M3X** [comment]
Wenn kein Bild durch den User hinterlegt wurde, könnte man ein Standard Bild (Pizza) hinterlegen. Würde schöner als das "No Image Available" aussehen.

![image](https://github.com/user-attachments/assets/e6da7ce6-293c-4e9a-aa3e-71a23fec7fda)

**Comment by N0M3X** [comment]
"Eintrag" statt "eintrag"

![image](https://github.com/user-attachments/assets/ba436899-acf0-4621-9a6c-5679813470fc)

**Comment by b0rn2my** [comment]
> Wenn kein Bild durch den User hinterlegt wurde, könnte man ein Standard Bild (Pizza) hinterlegen. Würde schöner als das "No Image Available" aussehen.
> 
> ![image](https://private-user-images.githubusercontent.com/166199140/364777255-e6da7ce6-293c-4e9a-aa3e-71a23fec7fda.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1OTg1NjAsIm5iZiI6MTcyNTU5ODI2MCwicGF0aCI6Ii8xNjYxOTkxNDAvMzY0Nzc3MjU1LWU2ZGE3Y2U2LTI5M2MtNGU5YS1hYTNlLTcxYTIzZmVjN2ZkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNlQwNDUxMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMjYzNmU5MzU3NDkxOTQ3NTkwNDRmY2VhZmRmMzI5YTBjODFhMmJhODZkZTFhOTllNGJmNmE2MGM0MWIxM2EwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gzCdlpR-hU3Ylaw72ablVfCdQ5idVTACk9n3b96H-2w)

Möchtest du hier ein Bild bereitstellen?

**Comment by N0M3X** [comment]
Klar, kann ich machen.

**Comment by b0rn2my** [comment]
Evtl auch für Zutaten ein globales default Image

**Comment by N0M3X** [comment]
Was sagst du zu einem dieser zwei Bilder für die Userbilder falls keines hinterlegt wurde...

![8-ayOYZRLOYCYag2w](https://github.com/user-attachments/assets/c310e09e-bc8b-4020-99bf-614c17fa64bb)
![8-zNWdT5lZR3Ka1yL](https://github.com/user-attachments/assets/e56bb8c0-cbc0-4182-a586-ba5763c8e4ee)

**Comment by b0rn2my** [comment]
Ich würde ein graues bevorzugen das die User einen Anreiz haben Bilder zu machen.

**Comment by N0M3X** [comment]
Was sagst du hierzu?

![8-SJjNBbS4waGMq8N](https://github.com/user-attachments/assets/b2a71df7-d7d9-4fe3-8c53-6f220f86602f)

**Comment by N0M3X** [comment]
Oder schlichter

![8-4c7zEV3aSlM4oe6](https://github.com/user-attachments/assets/825d4264-f8ae-41fc-b2d9-47e4ca05630f)

**Comment by b0rn2my** [comment]
Ich finde es super. Kann ich das verwenden?

Bitte per Email senden das ich die volle Qualität habe. Danke

**Comment by b0rn2my** [comment]
Das erste graue

**Comment by b0rn2my** [comment]
> Was sagst du hierzu?
> 
> 
> 
> ![8-SJjNBbS4waGMq8N](https://github.com/user-attachments/assets/b2a71df7-d7d9-4fe3-8c53-6f220f86602f)
> 
> 

Das oder?

**Comment by N0M3X** [comment]
Passt, ja hat schon kommerzielle Rechte. Dann schicke ich es dir per Email.
