### ISSUE TITLE
Änderung bei "Zutaten Vorlagen"

### ISSUE THREAD

**Issue by N0M3X** [b0rn2my/MyPizzaSessionApp#88]
So ist die Ansicht wenn man NICHT angemeldet ist. Dies passt soweit.

![image](https://github.com/user-attachments/assets/49707025-bac2-45b4-92d9-b84e6cea502b)

**Comment by N0M3X** [comment]
Größe von "Hinzufügen" anpassen, sodass es die gleiche Größe wie das "+" hat.

![image](https://github.com/user-attachments/assets/82cb2878-c5be-4e53-a9c4-97736304b637)

**Comment by N0M3X** [comment]
Und so ist die Ansicht wenn man angemeldet ist. Hier die Zutaten nach Rubrik und alphabetisch ordnen

![image](https://github.com/user-attachments/assets/c9d10d04-5359-4804-97d6-895d1a15395d)

**Comment by b0rn2my** [comment]
> Größe von "Hinzufügen" anpassen, sodass es die gleiche Größe wie das "+" hat.
> 
> ![image](https://private-user-images.githubusercontent.com/166199140/365062017-82cb2878-c5be-4e53-a9c4-97736304b637.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MDU1NzcsIm5iZiI6MTcyNTYwNTI3NywicGF0aCI6Ii8xNjYxOTkxNDAvMzY1MDYyMDE3LTgyY2IyODc4LWM1YmUtNGU1My1hOWM0LTk3NzM2MzA0YjYzNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNlQwNjQ3NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYmQxYTUzNGE3MTdjZjVhM2E3MDdiODVkYjljYjllNGM1MDNmZDIxZWY3YjY1Yzk5MDk0ZTAxMGJlOThiNjdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3GDFJ43bEi-uiA2ES4T9a_y-0Xp0344BFoUbkAyktDg)

Es hat die gleiche größe (Groß- und Kleinschreibung) ist der Unterschied.
Da passe ich nichts an.

**Comment by b0rn2my** [comment]
> Und so ist die Ansicht wenn man angemeldet ist. Hier die Zutaten nach Rubrik und alphabetisch ordnen
> 
> ![image](https://private-user-images.githubusercontent.com/166199140/365062487-c9d10d04-5359-4804-97d6-895d1a15395d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MDU2NTksIm5iZiI6MTcyNTYwNTM1OSwicGF0aCI6Ii8xNjYxOTkxNDAvMzY1MDYyNDg3LWM5ZDEwZDA0LTUzNTktNDgwNC05N2Q2LTg5NWQxYTE1Mzk1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNlQwNjQ5MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MzBmZmNlODk0NzFjODQ0NzZjYzYxNzJmYjZiZGU1YWRmZTA4MDYwZGNmYWQ4YjMyZTFkM2VmYmMzM2ExYjljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AOxvLKJywSIzuvk7OkMjWnW-grEYB1w6FltmII98OXA)

wird nun sortiert nach Kategorie und dann Name

**Comment by b0rn2my** [comment]
Redirekt ebenfalls angepasst
